import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { NotesProvider } from "@/contexts/NotesContext";
import { headers } from "next/headers";
import { getAllNotes } from "@/lib/db/note";
import SideBar from "@/components/SideBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// const notes: Note[] = [
//   {
//     id: "1",
//     user_id: "1",
//     title: "Meeting Notes",
//     content: "Discuss Q2 roadmap and assign tasks.",
//     updated_at: "2024-01-01",
//   },
//   {
//     id: "2",
//     user_id: "1",
//     title: "Shopping List",
//     content: "Milk, eggs, bread, coffee, bananas.",
//     updated_at: "2024-01-02",
//   },
//   {
//     id: "3",
//     user_id: "1",
//     title: "Book Ideas",
//     content: "Write a sci-fi novel set in 2150.",
//     updated_at: "2024-01-03",
//   },
//   {
//     id: "4",
//     user_id: "2",
//     title: "Workout Plan",
//     content: "Monday: chest. Wednesday: back. Friday: legs.",
//     updated_at: "2024-01-04",
//   },
//   {
//     id: "5",
//     user_id: "2",
//     title: "Travel Plans",
//     content: "Visit Japan in April, book flights early.",
//     updated_at: "2024-01-05",
//   },
// ];

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const notes: Note[] = await getAllNotes();
  // console.log(notes);

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="h-full flex flex-row">
        <NotesProvider initialNotes={notes}>
          <main className="flex-1">{children}</main>
        </NotesProvider>
      </body>
    </html>
  );
}
